[package]
name = "colorgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lds-rs = { path = "../lds-rs" }
palette = "0.6"
